#!/bin/bash

source_path=$HOME/Workspace/dotfiles
all_names=$(ls -p | grep -v / | grep -v soft | tr '\n' ' ')

soft () {
    for name in $@
    do
        #ln -s $source_path/$name $HOME/.$name
        if [[ $name == "vimrc" ]]; then
            ln -s $source_path/$name $HOME/.config/nvim/init.vim
        else
            ln -s $source_path/$name $HOME/.$name
        fi
    done
}

soft $all_names
